### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by wizhardhacker1** [aufzayed/HydraRecon#3] opened 2021-09-23 00:18 UTC
#] Take Screenshot for subdomains
Traceback (most recent call last):
  File "hydrarecon.py", line 257, in <module>
    take_screenshot(path_to_save)
  File "hydrarecon.py", line 160, in take_screenshot
    screenshot.screenshot(path)
  File "/home/das/DASTools/HydraRecon/core/basic/screenshot.py", line 12, in screenshot
    driver = Chrome(options=opts)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

![image](https://user-images.githubusercontent.com/46620390/134438682-51c19f72-2b22-406b-b37f-4b4e266aa44c.png)

**Comment by aufzayed** [comment] 2021-09-23 00:23
what's the distribution name and version?
what's the chrome or chromium driver version?

**Comment by wizhardhacker1** [comment] 2021-09-23 00:32
Ubuntu 20.04.3 Lts and version 95 from chromedriver.chromium.org

**Comment by aufzayed** [comment] 2021-09-23 00:39
remove your chrome and chrome driver and install chromium and chromium driver
command: `sudo apt install chromium-browser chromium-chromedriver`

**Comment by wizhardhacker1** [comment] 2021-09-23 00:45
Done same thing when it gets to screen shots section

**Comment by wizhardhacker1** [comment] 2021-09-23 00:47
#] Take Screenshot for subdomains
Traceback (most recent call last):
  File "hydrarecon.py", line 257, in <module>
    take_screenshot(path_to_save)
  File "hydrarecon.py", line 160, in take_screenshot
    screenshot.screenshot(path)
  File "/home/das/DASTools/HydraRecon/core/basic/screenshot.py", line 12, in screenshot
    driver = Chrome(options=opts)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/1753/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by aufzayed** [comment] 2021-09-23 00:47
thanks for your patience, I will work on an update for the screenshot module

**Comment by wizhardhacker1** [comment] 2021-09-23 00:50
thanks for all the hard work!

**Comment by aufzayed** [comment] 2021-09-23 06:57
please, execute these commands and send me the results
`chromedriver -v`
`chromium --version`

**Comment by wizhardhacker1** [comment] 2021-09-23 16:44
ChromeDriver 93.0.4577.82 (e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237})

**Comment by aufzayed** [comment] 2021-09-23 16:53
and chromium version

**Comment by wizhardhacker1** [comment] 2021-09-23 17:53
Chromium 93.0.4577.82 snap

**Comment by aufzayed** [comment] 2021-09-23 18:11
I tested the tool in the same environment, how do you run the tool?

**Comment by wizhardhacker1** [comment] 2021-09-24 00:25
sudo python3 hydrarecon.py --basic -d example.com-t 10 -o ~

**Comment by aufzayed** [comment] 2021-09-24 03:37
try it without sudo, and install requirements file without sudo too

`python3 -m pip install -r requirements.txt`

**Comment by wizhardhacker1** [comment] 2021-09-24 03:38
das@das:~/DASTools/HydraRecon$ python3 -m pip install -r requirements.txt
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (4.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (2.26.0)
Requirement already satisfied: selenium in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (3.141.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (1.26.6)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (0.4.3)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->-r requirements.txt (line 1)) (1.9.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from Jinja2->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from requests->-r requirements.txt (line 4)) (2.0.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 4)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages/certifi-2021.5.30-py3.8.egg (from requests->-r requirements.txt (line 4)) (2021.5.30)

**Comment by aufzayed** [comment] 2021-09-24 03:41
try to run the tool without sudo

**Comment by wizhardhacker1** [comment] 2021-09-24 04:07
__|   _| _ _ |__)_ _ _  _  
|  |\/(_|| (_|| \(-(_(_)| ) 
    /                       
Made with ♥ by Abdelrhman(@aufzayed)

[#] initializing HydraRecon report
[#] Collecting Subdomains
 | certspotter API
[!][certspotter] Runtime Error: string indices must be integers
 | crt.sh API
 | bufferover API
[!][dnsbufferover] Runtime Error 'NoneType' object is not iterable
 | hackertarget API
 | threatcrowd API
 | threatminer API
 | urlscan API
 | virustotal API
 | alienvault API
 | sublist3r API
 | anubis API
 | wayback API
Traceback (most recent call last):
  File "hydrarecon.py", line 254, in <module>
    subdomain_enum(host, path_to_save)
  File "hydrarecon.py", line 143, in subdomain_enum
    with open(f'{path}/hydra_report/subs.{domain}.txt', 'a') as subs_file:
PermissionError: [Errno 13] Permission denied: '/home/das/hydra_report/subs.google.com.txt'

**Comment by aufzayed** [comment] 2021-09-24 04:14
1- Delete the old report created by the tool with root privilege
2- run the tool again without sudo and test it with hackerone.com So it doesn't take up too much time

**Comment by wizhardhacker1** [comment] 2021-09-24 04:29
it is not creating a report... 

|__|   _| _ _ |__)_ _ _  _  
|  |\/(_|| (_|| \(-(_(_)| ) 
    /                       
Made with ♥ by Abdelrhman(@aufzayed)

[#] initializing HydraRecon report
[#] Collecting Subdomains
 | certspotter API
 | crt.sh API
 | bufferover API
[!][dnsbufferover] Runtime Error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
 | hackertarget API
[!][hackertraget] Runtime Error: HTTPSConnectionPool(host='api.hackertarget.com', port=443): Max retries exceeded with url: /hostsearch/?q=hackerone.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee9c551c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
 | threatcrowd API
 | threatminer API
 | urlscan API
 | virustotal API
 | alienvault API
 | sublist3r API
 | anubis API
 | wayback API
Traceback (most recent call last):
  File "hydrarecon.py", line 254, in <module>
    subdomain_enum(host, path_to_save)
  File "hydrarecon.py", line 143, in subdomain_enum
    with open(f'{path}/hydra_report/subs.{domain}.txt', 'a') as subs_file:
PermissionError: [Errno 13] Permission denied: '/home/das/hydra_report/subs.hackerone.com.txt'

**Comment by wizhardhacker1** [comment] 2021-09-24 04:31
run with sudo 

 _| _ _ |__)_ _ _  _  
|  |\/(_|| (_|| \(-(_(_)| ) 
    /                       
Made with ♥ by Abdelrhman(@aufzayed)

[#] initializing HydraRecon report
[#] Collecting Subdomains
 | certspotter API
 | crt.sh API
 | bufferover API
 | hackertarget API
 | threatcrowd API
 | threatminer API
 | urlscan API
 | virustotal API
 | alienvault API
 | sublist3r API
 | anubis API
 | wayback API
[#] Checking subdomains
 | mta-sts.forwarding.hackerone.com -> https://mta-sts.forwarding.hackerone.com :: 404
 | www.hackerone.com -> https://www.hackerone.com :: 200
 | mta-sts.managed.hackerone.com -> https://mta-sts.managed.hackerone.com :: 404
 | gslink.hackerone.com -> https://gslink.hackerone.com :: 404
 | mta-sts.forwarding.hackerone.com -> https://mta-sts.forwarding.hackerone.com :: 404
 | mta-sts.managed.hackerone.com -> https://mta-sts.managed.hackerone.com :: 404
 | mta-sts.hackerone.com -> https://mta-sts.hackerone.com :: 404
 | gslink.hackerone.com -> https://gslink.hackerone.com :: 404
 | www.hackerone.com -> https://www.hackerone.com :: 200
 | mta-sts.hackerone.com -> https://mta-sts.hackerone.com :: 404
 | support.hackerone.com -> https://support.hackerone.com :: 200
 | docs.hackerone.com -> https://docs.hackerone.com :: 200
 | api.hackerone.com -> https://api.hackerone.com :: 200
 | docs.hackerone.com -> https://docs.hackerone.com :: 200
 | support.hackerone.com -> https://support.hackerone.com :: 200
 | resources.hackerone.com -> http://resources.hackerone.com :: 404
 | api.hackerone.com -> https://api.hackerone.com :: 200
[#] Take Screenshot for subdomains
Traceback (most recent call last):
  File "hydrarecon.py", line 257, in <module>
    take_screenshot(path_to_save)
  File "hydrarecon.py", line 160, in take_screenshot
    screenshot.screenshot(path)
  File "/home/das/DASTools/HydraRecon/core/basic/screenshot.py", line 12, in screenshot
    driver = Chrome(options=opts)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/1753/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by aufzayed** [comment] 2021-09-24 04:33
it's a permission error, delete hydra_report directory and try again, or change output path to another directory or current directory

do not forget to run it without sudo

**Comment by wizhardhacker1** [comment] 2021-09-24 04:40
there is no report to delete..

I ran with and with out sudo 1st one was with out sudo 2nd one was with sudo again

it is never creating a report

**Comment by aufzayed** [comment] 2021-09-24 04:44
if you don't delete the old directory the tool will write the new data on it.

the owner of the old directory is root, 
so you can't write the new data on it as a low privileged user

**Comment by wizhardhacker1** [comment] 2021-09-24 05:03
what folder do you want me to delete? 
![image](https://user-images.githubusercontent.com/46620390/134620975-28afe9fb-54d6-4212-80f5-08e3327016a3.png)

**Comment by aufzayed** [comment] 2021-09-24 05:16
delete hydra_report folder in your home directory

**Comment by wizhardhacker1** [comment] 2021-09-24 05:48
|__|   _| _ _ |__)_ _ _  _  
|  |\/(_|| (_|| \(-(_(_)| ) 
    /                       
Made with ♥ by Abdelrhman(@aufzayed)

[#] initializing HydraRecon report
[#] Collecting Subdomains
 | certspotter API
 | crt.sh API
 | bufferover API
 | hackertarget API
 | threatcrowd API
 | threatminer API
 | urlscan API
 | virustotal API
 | alienvault API
 | sublist3r API
 | anubis API
 | wayback API
[!][wayback] Runtime Error: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /cdx/search/cdx?url=%2A.hackerone.com%2F%2A&output=json&collapse=urlkey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7754606d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[#] Checking subdomains
 | mta-sts.managed.hackerone.com -> https://mta-sts.managed.hackerone.com :: 404
[#] Take Screenshot for subdomains
 | screenshot http___mta-sts_managed_hackerone_com_.html ok
[#] Port Scanning...
[#] Port Scanning Done!

**Comment by aufzayed** [comment] 2021-09-24 05:54
The tool worked successfully.
Do not use sudo.
some runtime errors will happen due to different network problems.
the tool will save the results in the hydra_report folder in the home dir unless you specified another path

**Comment by wizhardhacker1** [comment] 2021-09-24 06:16
k thanks.. PS: sudo was the only way it worked

**Comment by aufzayed** [comment] 2021-09-24 06:26
The first problem had nothing to do with Chrome, when I looked for the cause of the second problem, I found that sometimes problems occur when Chrome is running with root privilege.

**Comment by aufzayed** [comment] 2021-09-24 06:28
i will close the issue now

**Closed as completed** 2021-09-24 06:37 UTC
